// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: tests/types/types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CustomType represents a custom type for testing
type CustomType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value   int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Enabled bool   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
}

func (x *CustomType) Reset() {
	*x = CustomType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tests_types_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomType) ProtoMessage() {}

func (x *CustomType) ProtoReflect() protoreflect.Message {
	mi := &file_tests_types_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomType.ProtoReflect.Descriptor instead.
func (*CustomType) Descriptor() ([]byte, []int) {
	return file_tests_types_types_proto_rawDescGZIP(), []int{0}
}

func (x *CustomType) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CustomType) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *CustomType) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

var File_tests_types_types_proto protoreflect.FileDescriptor

var file_tests_types_types_proto_rawDesc = []byte{
	0x0a, 0x17, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x74, 0x65, 0x73, 0x74, 0x73,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x50, 0x0a, 0x0a, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6f, 0x72, 0x61, 0x6e, 0x70, 0x69, 0x78, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x2d, 0x66, 0x6c, 0x61,
	0x67, 0x73, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tests_types_types_proto_rawDescOnce sync.Once
	file_tests_types_types_proto_rawDescData = file_tests_types_types_proto_rawDesc
)

func file_tests_types_types_proto_rawDescGZIP() []byte {
	file_tests_types_types_proto_rawDescOnce.Do(func() {
		file_tests_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_tests_types_types_proto_rawDescData)
	})
	return file_tests_types_types_proto_rawDescData
}

var file_tests_types_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_tests_types_types_proto_goTypes = []interface{}{
	(*CustomType)(nil), // 0: tests.types.CustomType
}
var file_tests_types_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tests_types_types_proto_init() }
func file_tests_types_types_proto_init() {
	if File_tests_types_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tests_types_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tests_types_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tests_types_types_proto_goTypes,
		DependencyIndexes: file_tests_types_types_proto_depIdxs,
		MessageInfos:      file_tests_types_types_proto_msgTypes,
	}.Build()
	File_tests_types_types_proto = out.File
	file_tests_types_types_proto_rawDesc = nil
	file_tests_types_types_proto_goTypes = nil
	file_tests_types_types_proto_depIdxs = nil
}
