package module

import (
	"fmt"
	"sort"
	"strings"
	"text/template"

	pgs "github.com/lyft/protoc-gen-star/v2"
	pgsgo "github.com/lyft/protoc-gen-star/v2/lang/go"
	"github.com/oranpix/protoc-gen-go-flags/flags"
)

func Flags() *Module {
	return &Module{
		ModuleBase:      &pgs.ModuleBase{},
		imports:         make(map[string]struct{}),
		packageAliases:  make(map[string]string),
		nameCollisions:  make(map[string]int),
		normalizedPaths: make(map[string]struct{}),
	}
}

// ImportInfo stores normalized import information
type ImportInfo struct {
	Path  string
	Alias string
}

type Module struct {
	*pgs.ModuleBase
	ctx             pgsgo.Context
	tpl             *template.Template
	imports         map[string]struct{}
	packageAliases  map[string]string // import path -> alias (if needed)
	nameCollisions  map[string]int    // package name -> collision count
	normalizedPaths map[string]struct{}
}

type goTypeRef struct {
	name       string
	importPath string
	prefix     string
}

func (m *Module) Name() string {
	return "flags"
}

func (m *Module) InitContext(c pgs.BuildContext) {
	m.ModuleBase.InitContext(c)
	m.ctx = pgsgo.InitContext(c.Parameters())

	m.resetImportState()

	tpl := template.New("fields").Funcs(map[string]interface{}{
		"package": m.ctx.PackageName,
		"name":    m.ctx.Name,
		"methodName": func(m pgs.Message) string {
			var private bool
			_, _ = m.Extension(flags.E_Unexported, &private)
			if private {
				return "_AddFlags"
			}
			return "AddFlags"
		},
		"defaultMethodName": func(m pgs.Message) string {
			var private bool
			_, _ = m.Extension(flags.E_Unexported, &private)
			if private {
				return "_SetDefaults"
			}
			return "SetDefaults"
		},
		"comment": func(s string) string {
			var out string
			parts := strings.Split(s, "\n")
			for i, v := range parts {
				if i == len(parts)-1 && v == "" {
					return out
				}
				out += "//" + v + "\n"
			}
			return out
		},
		"imports": func() string {
			return m.generateImports()
		},
		"enabled": func(msg pgs.Message) bool {
			return m.messageGeneratesFlagMethods(msg)
		},
		"flags": func(f pgs.Field) string {
			return m.genFieldFlags(f)
		},
		"defaults": func(f pgs.Field) string {
			return m.genFieldDefaults(f)
		},
	})
	m.tpl = template.Must(tpl.Parse(defaultsTpl))
}

func (m *Module) Execute(f pgs.File, _ map[string]pgs.Package) []pgs.Artifact {
	if m.shouldGenerate(f) {
		m.generate(f)
	}
	return m.Artifacts()
}

func (m *Module) generate(f pgs.File) {
	if len(f.Messages()) == 0 {
		return
	}
	m.resetImportState()
	for _, msg := range f.Messages() {
		m.Check(msg)
	}
	name := m.ctx.OutputPath(f).SetExt(".flags.go")
	m.AddGeneratorTemplateFile(name.String(), m.tpl, f)
}

const defaultsTpl = `{{ comment .SyntaxSourceCodeInfo.LeadingComments }}
{{ range .SyntaxSourceCodeInfo.LeadingDetachedComments }}
{{ comment . }}
{{ end }}
// Code generated by protoc-gen-go-flags. DO NOT EDIT.

package {{ package . }}

import (
	"github.com/spf13/pflag"
	"github.com/oranpix/protoc-gen-go-flags/utils"
    "github.com/oranpix/protoc-gen-go-flags/types"
    "github.com/oranpix/protoc-gen-go-flags/flags"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"

	{{ imports }}
)

var (
	_ = pflag.NewFlagSet
	_ = utils.MustDecodeBase64
    _ = types.Bool
    _ = flags.Flagger(nil)
	_ = wrapperspb.String
	_ = (*durationpb.Duration)(nil)
	_ = (*timestamppb.Timestamp)(nil)
)

{{ range .AllMessages }}
{{ if enabled . }}
func (x *{{ name . }}) {{ methodName . }}(fs *pflag.FlagSet, opts ...flags.Option) {
	builder := flags.NewNameBuilder(opts...)
	_ = builder
	{{- range .Fields }}
		{{- flags . }}
	{{- end }}
}

func (x *{{ name . }}) {{ defaultMethodName . }}() {
	{{- range .Fields }}
		{{- defaults . }}
	{{- end }}
}
{{- end }}
{{ end }}
`

func (m *Module) resetImportState() {
	m.imports = make(map[string]struct{})
	m.packageAliases = make(map[string]string)
	m.normalizedPaths = make(map[string]struct{})

	// Standard package names that are always imported by the generated template.
	m.nameCollisions = map[string]int{
		"pflag":       0,
		"utils":       0,
		"types":       0,
		"flags":       0,
		"durationpb":  0,
		"timestamppb": 0,
		"wrapperspb":  0,
	}
}

func (m *Module) messageGeneratesFlagMethods(msg pgs.Message) bool {
	var (
		disabled   bool
		hasFlag    bool
		allowEmpty bool
	)
	for _, field := range msg.Fields() {
		var fd flags.FieldFlags
		ok, err := field.Extension(flags.E_Value, &fd)
		if err == nil && ok && !field.InRealOneOf() {
			hasFlag = true
			break
		}
	}
	_, _ = msg.Extension(flags.E_Disabled, &disabled)
	_, _ = msg.Extension(flags.E_AllowEmpty, &allowEmpty)

	return !disabled && (hasFlag || allowEmpty)
}

func (m *Module) messageGeneratesPublicAddFlags(msg pgs.Message) bool {
	var unexported bool
	_, _ = msg.Extension(flags.E_Unexported, &unexported)
	return !unexported && m.messageGeneratesFlagMethods(msg)
}

// normalizeImports processes all imports and assigns aliases to packages with name collisions
// This is based on the enumPackages implementation in example.go
func (m *Module) normalizeImports() {
	importPaths := m.sortedImportPaths()
	for _, importPath := range importPaths {
		if _, ok := m.normalizedPaths[importPath]; ok {
			continue
		}

		// Get the package name from the import path
		pkgName := m.getPackageNameFromPath(importPath)

		// Check if this package name has collision
		if collision, ok := m.nameCollisions[pkgName]; ok {
			// Package name collides, assign an alias
			m.nameCollisions[pkgName] = collision + 1
			alias := fmt.Sprintf("%s%d", pkgName, m.nameCollisions[pkgName])
			m.packageAliases[importPath] = alias
		} else {
			// First occurrence of this package name
			m.nameCollisions[pkgName] = 0
			// No alias needed for first occurrence
		}

		m.normalizedPaths[importPath] = struct{}{}
	}
}

// generateImports generates the import statements with proper aliases
func (m *Module) generateImports() string {
	m.normalizeImports()

	var imports strings.Builder
	for _, importPath := range m.sortedImportPaths() {
		if alias, ok := m.packageAliases[importPath]; ok {
			imports.WriteString(fmt.Sprintf("%s \"%s\"\n", alias, importPath))
		} else {
			imports.WriteString(fmt.Sprintf("\"%s\"\n", importPath))
		}
	}
	return imports.String()
}

func (m *Module) sortedImportPaths() []string {
	importPaths := make([]string, 0, len(m.imports))
	for importPath := range m.imports {
		importPaths = append(importPaths, importPath)
	}
	sort.Strings(importPaths)
	return importPaths
}

// getPackageNameFromPath extracts the package name from an import path
func (m *Module) getPackageNameFromPath(importPath string) string {
	parts := strings.Split(importPath, "/")
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return importPath
}

func (m *Module) formatTypeRef(ref goTypeRef) string {
	name := ref.name
	if ref.importPath != "" {
		pkg := m.getPackageNameFromPath(ref.importPath)
		if alias, ok := m.packageAliases[ref.importPath]; ok {
			pkg = alias
		}
		name = pkg + "." + name
	}
	return ref.prefix + name
}

func (m *Module) typeRefForField(f pgs.Field) goTypeRef {
	typeName := m.ctx.Type(f).Value().String()
	ref := goTypeRef{name: typeName}

	for {
		switch {
		case strings.HasPrefix(ref.name, "[]"):
			ref.prefix += "[]"
			ref.name = strings.TrimPrefix(ref.name, "[]")
		case strings.HasPrefix(ref.name, "*"):
			ref.prefix += "*"
			ref.name = strings.TrimPrefix(ref.name, "*")
		default:
			goto typePartsDone
		}
	}

typePartsDone:
	typ := f.Type()

	if typ.IsEmbed() {
		msg := typ.Embed()
		ref.name = m.ctx.Name(msg).String()
		if m.ctx.ImportPath(msg).String() != m.ctx.ImportPath(f).String() {
			ref.importPath = m.ctx.ImportPath(msg).String()
		}
		return ref
	}

	if typ.IsEnum() {
		enum := typ.Enum()
		ref.name = m.ctx.Name(enum).String()
		if m.ctx.ImportPath(enum).String() != m.ctx.ImportPath(f).String() {
			ref.importPath = m.ctx.ImportPath(enum).String()
		}
		return ref
	}

	if typ.IsRepeated() && typ.Element() != nil {
		el := typ.Element()
		if el.IsEmbed() {
			msg := el.Embed()
			ref.name = m.ctx.Name(msg).String()
			if m.ctx.ImportPath(msg).String() != m.ctx.ImportPath(f).String() {
				ref.importPath = m.ctx.ImportPath(msg).String()
			}
			return ref
		}
		if el.IsEnum() {
			enum := el.Enum()
			ref.name = m.ctx.Name(enum).String()
			if m.ctx.ImportPath(enum).String() != m.ctx.ImportPath(f).String() {
				ref.importPath = m.ctx.ImportPath(enum).String()
			}
			return ref
		}
	}

	return ref
}

// getFieldTypeName returns the Go type name for a field using import aliases assigned for this file.
func (m *Module) getFieldTypeName(f pgs.Field) string {
	return m.formatTypeRef(m.typeRefForField(f))
}
