// Code generated by protoc-gen-go-flags. DO NOT EDIT.

package proto

import (
	"github.com/oranpix/protoc-gen-go-flags/flags"
	"github.com/oranpix/protoc-gen-go-flags/types"
	"github.com/oranpix/protoc-gen-go-flags/utils"
	"github.com/spf13/pflag"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ = pflag.NewFlagSet
	_ = utils.MustDecodeBase64
	_ = types.Bool
	_ = flags.Flagger(nil)
	_ = wrapperspb.String
	_ = (*durationpb.Duration)(nil)
	_ = (*timestamppb.Timestamp)(nil)
)

func (x *ServiceConfig) AddFlags(fs *pflag.FlagSet, opts ...flags.Option) {
	builder := flags.NewNameBuilder(opts...)
	_ = builder
	fs.StringVarP(&x.Host, builder.Build("host"), "", x.Host, "Service host address")

	fs.Int32VarP(&x.Port, builder.Build("port"), "", x.Port, "Service port number")

	if x.Timeout == nil {
		x.Timeout = new(durationpb.Duration)
	}

	fs.VarP(types.Duration(x.Timeout), builder.Build("timeout"), "", "Connection timeout")

	fs.Int32VarP(&x.MaxConnections, builder.Build("max-connections"), "", x.MaxConnections, "Maximum number of connections")

	fs.BoolVarP(&x.TlsEnabled, builder.Build("tls"), "", x.TlsEnabled, "Enable TLS")

}

func (x *ServiceConfig) SetDefaults() {
	if x.Host == "" {
		x.Host = "localhost"
	}

	if x.Port == 0 {
		x.Port = 8080
	}

	if x.Timeout == nil {
		x.Timeout = &durationpb.Duration{Seconds: 30, Nanos: 0}
	}
	if x.MaxConnections == 0 {
		x.MaxConnections = 100
	}

}
