// Code generated by protoc-gen-go-flags. DO NOT EDIT.

package proto

import (
	"github.com/oranpix/protoc-gen-go-flags/flags"
	"github.com/oranpix/protoc-gen-go-flags/types"
	"github.com/oranpix/protoc-gen-go-flags/utils"
	"github.com/spf13/pflag"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ = pflag.NewFlagSet
	_ = utils.MustDecodeBase64
	_ = types.Bool
	_ = flags.Flagger(nil)
	_ = wrapperspb.String
	_ = (*durationpb.Duration)(nil)
	_ = (*timestamppb.Timestamp)(nil)
)

func (x *ServerConfig) AddFlags(fs *pflag.FlagSet, opts ...flags.Option) {
	builder := flags.NewNameBuilder(opts...)
	_ = builder
	fs.StringVarP(&x.Host, builder.Build("host"), "H", x.Host, "Server host address")

	fs.Int32VarP(&x.Port, builder.Build("port"), "p", x.Port, "Server port number")

	fs.BoolVarP(&x.Debug, builder.Build("debug"), "d", x.Debug, "Enable debug mode")

}

func (x *ServerConfig) SetDefaults() {
	if x.Host == "" {
		x.Host = "localhost"
	}

	if x.Port == 0 {
		x.Port = 8080
	}

}
