// Code generated by protoc-gen-go-flags. DO NOT EDIT.

package proto

import (
	"github.com/oranpix/protoc-gen-go-flags/flags"
	"github.com/oranpix/protoc-gen-go-flags/types"
	"github.com/oranpix/protoc-gen-go-flags/utils"
	"github.com/spf13/pflag"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ = pflag.NewFlagSet
	_ = utils.MustDecodeBase64
	_ = types.Bool
	_ = flags.Flagger(nil)
	_ = wrapperspb.String
	_ = (*durationpb.Duration)(nil)
	_ = (*timestamppb.Timestamp)(nil)
)

func (x *AdvancedConfig) AddFlags(fs *pflag.FlagSet, opts ...flags.Option) {
	builder := flags.NewNameBuilder(opts...)
	_ = builder
	fs.StringVarP(&x.Name, builder.Build("name"), "n", x.Name, "Application name")

	fs.Int32VarP(&x.WorkerCount, builder.Build("workers"), "w", x.WorkerCount, "Number of worker threads")

	fs.Int64VarP(&x.MaxMemory, builder.Build("max-memory"), "", x.MaxMemory, "Maximum memory in bytes")

	fs.Uint32VarP(&x.RateLimit, builder.Build("rate-limit"), "", x.RateLimit, "Maximum requests per second")

	fs.Float32VarP(&x.Ratio, builder.Build("ratio"), "", x.Ratio, "Processing ratio (0.0 to 1.0)")

	fs.BoolVarP(&x.Enabled, builder.Build("enabled"), "e", x.Enabled, "Enable the feature")

	fs.BytesBase64VarP(&x.ApiKey, builder.Build("api-key"), "", x.ApiKey, "API key (base64 encoded)")

	if x.Timeout == nil {
		x.Timeout = new(durationpb.Duration)
	}

	fs.VarP(types.Duration(x.Timeout), builder.Build("timeout"), "t", "Connection timeout (e.g., 30s, 5m, 1h)")

	if x.CreatedAt == nil {
		x.CreatedAt = new(timestamppb.Timestamp)
	}

	fs.VarP(types.Timestamp(x.CreatedAt, []string{"RFC3339", "ISO8601"}), builder.Build("created-at"), "", "Creation timestamp (RFC3339 format)")

	fs.StringSliceVarP(&x.Servers, builder.Build("servers"), "s", x.Servers, "List of server addresses (comma-separated or multiple flags)")

	fs.Int32SliceVarP(&x.Ports, builder.Build("ports"), "", x.Ports, "List of port numbers")

	fs.StringToStringVarP(&x.Labels, builder.Build("labels"), "l", x.Labels, "Key-value labels (JSON or key=value,key2=value2 format)")

	fs.VarP(types.StringToInt32(&x.Limits), builder.Build("limits"), "", "Resource limits (e.g., cpu=1000,memory=2048)")

	fs.VarP(types.Enum(&x.LogLevel), builder.Build("log-level"), "", "Logging level ( LOG_LEVEL_DEBUG, LOG_LEVEL_INFO, LOG_LEVEL_WARN, LOG_LEVEL_ERROR)")

	fs.BoolVarP(&x.DeprecatedFlag, builder.Build("old-feature"), "", x.DeprecatedFlag, "Old feature flag")

	fs.MarkDeprecated("old-feature", "Use --enabled instead")

	fs.StringVarP(&x.InternalToken, builder.Build("internal-token"), "", x.InternalToken, "Internal authentication token")

	fs.MarkHidden("internal-token")

}

func (x *AdvancedConfig) SetDefaults() {
	if x.Name == "" {
		x.Name = "AdvancedApp"
	}

	if x.WorkerCount == 0 {
		x.WorkerCount = 4
	}

	if x.MaxMemory == 0 {
		x.MaxMemory = 1073741824
	}

	if x.RateLimit == 0 {
		x.RateLimit = 100
	}

	if x.Ratio == 0 {
		x.Ratio = 0.8
	}

	if len(x.ApiKey) == 0 {
		x.ApiKey = utils.MustDecodeBase64("ZGVmYXVsdGtleQ==")
	}
	if x.Timeout == nil {
		x.Timeout = &durationpb.Duration{Seconds: 30, Nanos: 0}
	}
	if x.CreatedAt == nil {
		x.CreatedAt = &timestamppb.Timestamp{Seconds: 1704067200, Nanos: 0}
	}

	if len(x.Servers) == 0 {
		x.Servers = []string{"localhost:8080"}
	}

	if len(x.Ports) == 0 {
		x.Ports = []int32{8080, 8081}
	}

	if x.LogLevel == 0 {
		x.LogLevel = 2
	}

	if x.InternalToken == "" {
		x.InternalToken = "secret"
	}

}
