// Code generated by protoc-gen-go-flags. DO NOT EDIT.

package proto

import (
	"github.com/oranpix/protoc-gen-go-flags/flags"
	"github.com/oranpix/protoc-gen-go-flags/types"
	"github.com/oranpix/protoc-gen-go-flags/utils"
	"github.com/spf13/pflag"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ = pflag.NewFlagSet
	_ = utils.MustDecodeBase64
	_ = types.Bool
	_ = flags.Flagger(nil)
	_ = wrapperspb.String
	_ = (*durationpb.Duration)(nil)
	_ = (*timestamppb.Timestamp)(nil)
)

func (x *ServerConfig) AddFlags(fs *pflag.FlagSet, opts ...flags.Option) {
	builder := flags.NewNameBuilder(opts...)
	_ = builder
	fs.StringVarP(&x.Host, builder.Build("host"), "H", x.Host, "Server host address")

	fs.Int32VarP(&x.Port, builder.Build("port"), "p", x.Port, "Server port number")

	fs.BoolVarP(&x.Https, builder.Build("https"), "s", x.Https, "Enable HTTPS")

}

func (x *ServerConfig) SetDefaults() {
	if x.Host == "" {
		x.Host = "localhost"
	}

	if x.Port == 0 {
		x.Port = 8080
	}

}

func (x *DatabaseConfig) AddFlags(fs *pflag.FlagSet, opts ...flags.Option) {
	builder := flags.NewNameBuilder(opts...)
	_ = builder
	fs.StringVarP(&x.Url, builder.Build("database-url"), "u", x.Url, "Database connection URL")

	fs.Int32VarP(&x.MaxConnections, builder.Build("database-max-connections"), "", x.MaxConnections, "Maximum number of database connections")

}

func (x *DatabaseConfig) SetDefaults() {
	if x.Url == "" {
		x.Url = "postgres://localhost:5432/defaultdb"
	}

	if x.MaxConnections == 0 {
		x.MaxConnections = 10
	}

}

func (x *LoggingConfig) AddFlags(fs *pflag.FlagSet, opts ...flags.Option) {
	builder := flags.NewNameBuilder(opts...)
	_ = builder
	fs.StringVarP(&x.Level, builder.Build("logging-level"), "l", x.Level, "Log level (debug, info, warn, error)")

	fs.StringVarP(&x.Format, builder.Build("logging-format"), "", x.Format, "Log format (json or text)")

}

func (x *LoggingConfig) SetDefaults() {
	if x.Level == "" {
		x.Level = "info"
	}

	if x.Format == "" {
		x.Format = "text"
	}

}

func (x *AppConfig) AddFlags(fs *pflag.FlagSet, opts ...flags.Option) {
	builder := flags.NewNameBuilder(opts...)
	_ = builder
	if x.Server == nil {
		x.Server = new(ServerConfig)
	}

	if v, ok := interface{}(x.Server).(flags.Flagger); ok {
		v.AddFlags(fs, append(opts, flags.WithPrefix("server"))...)
	}

	if x.Database == nil {
		x.Database = new(DatabaseConfig)
	}

	if v, ok := interface{}(x.Database).(flags.Flagger); ok {
		v.AddFlags(fs, append(opts, flags.WithPrefix("db"))...)
	}

	if x.Logging == nil {
		x.Logging = new(LoggingConfig)
	}

	if v, ok := interface{}(x.Logging).(flags.Flagger); ok {
		v.AddFlags(fs, append(opts, flags.WithPrefix("log"))...)
	}

}

func (x *AppConfig) SetDefaults() {
	if x.Server == nil {
		x.Server = new(ServerConfig)
	}

	if v, ok := interface{}(x.Server).(flags.Defaulter); ok {
		v.SetDefaults()
	}

	if x.Database == nil {
		x.Database = new(DatabaseConfig)
	}

	if v, ok := interface{}(x.Database).(flags.Defaulter); ok {
		v.SetDefaults()
	}

	if x.Logging == nil {
		x.Logging = new(LoggingConfig)
	}

	if v, ok := interface{}(x.Logging).(flags.Defaulter); ok {
		v.SetDefaults()
	}

}
