// Code generated by protoc-gen-go-flags. DO NOT EDIT.

package utils

import (
	"github.com/oranpix/protoc-gen-go-flags/flags"
	"github.com/oranpix/protoc-gen-go-flags/types"
	"github.com/oranpix/protoc-gen-go-flags/utils"
	"github.com/spf13/pflag"
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ = pflag.NewFlagSet
	_ = utils.MustDecodeBase64
	_ = types.Bool
	_ = flags.Flagger(nil)
	_ = wrapperspb.String
	_ = (*durationpb.Duration)(nil)
	_ = (*timestamppb.Timestamp)(nil)
)

func (x *SimpleMessage) AddFlags(fs *pflag.FlagSet, opts ...flags.Option) {
	builder := flags.NewNameBuilder(opts...)
	_ = builder
	fs.StringVarP(&x.Name, builder.Build("name"), "", x.Name, "Name parameter")

	fs.VarP(types.TimestampSlice(&x.CreatedAt, []string{"RFC3339", "ISO8601"}), builder.Build("created-at"), "", "Creation timestamp")

}

func (x *SimpleMessage) SetDefaults() {
	if len(x.CreatedAt) == 0 {
		x.CreatedAt = []*timestamppb.Timestamp{&timestamppb.Timestamp{Seconds: 1672531200, Nanos: 0}}
	}

}
